name = "Connor Rubin"
title = "Technical Product Manager"
street = "603 HWY 141"
city = "White Salmon"
state = "Washington"
zipcode = "98672"
address = "603 HWY 141, White Salmon, WA 98672"
phone = "+1 (216) 554-1740"
email = "csrubin@gmail.com"
linked_in = "https://www.linkedin.com/in/connor-rubin/"
about_me = """
Wide-ranging experiences, passion for technology and sustainability, and a penchant for active discovery have led me to become a
competent generalist who isn't afraid to dig into the details while maintaining focus on the bigger picture.
I am a curious, detailed-oriented, and pragmatic worker with hopes to use my skills to
further sustainability goals using technology.
"""