name = "Connor Rubin"
title = "Technical Product Manager"
street = "2259 Sandalwood Dr"
city = "Twinsburg"
state = "Ohio"
zipcode = "44087"
address = "2259 Sandalwood Dr, Twinsburg, OH 44087"
phone = "+1 (216) 554-1740"
email = "csrubin@gmail.com"
linked_in = "https://www.linkedin.com/in/connor-rubin-58a98b7a/"
about_me = """This is my about me description in about.toml"""