school = "The Ohio State University"
degree = "Bachelor of Science"
major = "Electrical Engineering (Control Systems), with Honors Distinction"
minor = "Environment, Economy, Development, and Sustainability (EEDS)"
gpa = 3.60
start = 2015-08-24
end = 2019-12-15
relevant_coursework = [
    "Real Time Robotics Systems",
    "Powertrain Control Systems",
    "Machine Learning for ECE",
    "Sustainable Energy and Power Systems",
    "Empowering the Entrepreneurial Electrical and Computer Engineer",
    "Business and Sustainability",
]

projects = [
    "Precision Agriculture Mesh Sensor Network",
    "Autonomous \"Spaceport\" Robot",
    "Model LIDAR Autonomous Vehicle (Smart City)",
    "Alexa Universal Remote",
    "RFID Resident Check-In Device"
]

activities = [
    "Electronics Club (President)",
    "OHI/O Make-a-thon (Chairman)",
    "Model Smart City Design Team"
]
