["Product Manager"]
company = "Superpedestrian"
title = "Product Manager"
start = 2021-06-01
end = 2022-02-17
departments = ["Embedded Systems", "R&D", "AI/ML"]
work_items = [
    "Specified, planned, and prioritized work across three independent teams (Research & Development, Embedded Systems, Embedded Test) to integrate new technology and bring to market",
    "Translated problem statements from operations teams into feature specifications",
    "Communicated critical technical topics to non-technical teams throughout the organization",
    "Scoped and scheduled engineering feature development to support high profile technology demos",
    "Introduced documentation and process for feature development",
    "Managed new team integration to company post-acquisition (acquired R&D department)",
    "Groomed software task backlog and specified new work specifically in support of cross-team integration",
    "Continued improvement of test report generation and analytics"
]
key_achievements = """Led entire new product introduction process of high accuracy location technology for LEVs
(from company partner acquisition through system integration and launch). Directed technology demo, resulting in
winning high-value permit to operate in Chicago, IL. Standardized new feature integration process across hardware
and software teams."""

["Test Engineer"]
company = "Superpedestrian"
title = "Embedded Systems Test Engineer"
start = 2020-02-17
end = 2021-06-01
departments = ["Embedded Systems"]
work_items = [
    "Developed and maintained hardware-in-the-loop test fixture and software tests for smart LEV platform" ,
    "Built document-based manufacturing test database and supporting ETL processes" ,
    "Managed vehicle firmware release process (performance testing and validation, engineering change orders, etc.)",
    "Designed and specified manufacturing test fixture to support offline firmware updates during final assembly",
    "Streamlined communications and troubleshot manufacturing issues with partners in China"
]
key_achievements = "Increased fault injection and stability test coverage by over 10x. Improved throughput of electronics manufacturing line by 35% through cycle time reduction analysis using test database."

["Technical Sales Intern"]
company = "Keyence America"
title = "Sales Engineer (Intern)"
start = 2019-06-01
end = 2019-08-05
work_items = [
    "Generated 30+ sales leads on a range of highly technical industrial automation products using a proprietary customer relationship management system",
    "Assisted sales engineers during various in-person sales calls/product demonstrations"
]
key_achievements = "Triggered over $120,000 in sales for vision-based sensors and laser markers."

["Undergraduate Researcher"]
company = "The Ohio State University"
title = "Lead Undergraduate Research Assistant"
start = 2018-06-01
end = 2018-08-25
departments = ["Center for High Performance Power Electronics"]
work_items = [
    "Directed undergraduate research team in developing a cyber-physical power grid testbed",
    "Designed testbed for real-time cyber-attack analysis and defense strategy development",
]
key_achievements = "Resultant research published by IEEE via the North American Power Symposium."
link = "https://ieeexplore.ieee.org/document/9000312"
file = "/static/content/NAPS2019_paper_15.pdf"


["Product Development Intern"]
company = "Tech4Imaging"
title = "Product Development Engineer (Intern)"
start = 2017-09-01
end = 2017-11-22
work_items = [
    "Designed and operated test equipment for novel 3D imaging/nondestructive testing technology",
    "Furthered multi-phase mass-flow meter based on ‘electrical capacitance volume tomography",
    "Modified plumbing system to incorporate stratified flow into a multiphase flow loop for testing"
]

key_achievements = "Determined empirical relationship between capacitance and liquid volume."

