[Superpedestrian]
employment_period = 'February 2020 - February 2022'

[Superpedestrian.'Product Manager']
departments = ['Embedded Systems', 'R&D', 'AI/ML']
responsibilities = [
    'Specified, planned, and prioritized work across three independent teams (Research & Development, Embedded Systems, Embedded Test) to integrate new technology and bring to market',
    'Translated problem statements from operations teams into feature specifications',
    'Communicated critical technical topics to non-technical teams throughout the organization',
    'Scoped and scheduled engineering feature development to support high profile technology demos'
]
key_achievements = 'Led entire new product introduction process of high accuracy location technology for LEVs (from company partner acquisition through system integration and launch). Directed technology demo, resulting in winning high-value permit to operate in Chicago, IL.'

[Superpedestrian.'Associate Product Manager']
departments = ['Embedded Systems']
responsibilities = [
    "Introduced documentation and process for feature development",
    "Managed new team integration to company post-acquisition (acquired R&D department)",
    "Groomed software task backlog and specified new work specifically in support of cross-team integration", 
    "Continued improvement of test report generation and analytics"
]
key_achievements = 'Standardized new feature integration process across hardware and software teams.'

[Superpedestrian."Test Engineer"]
departments = ['Embedded Systems']
responsibilities = [
    "Developed and maintained hardware-in-the-loop test fixture and software tests for smart LEV platform" ,
    "Built document-based manufacturing test database and supporting ETL processes" ,
    "Managed vehicle firmware release process (performance testing and validation, engineering change orders, etc.)",
    "Designed and specified manufacturing test fixture to support offline firmware updates during final assembly",
    "Streamlined communications and troubleshot manufacturing issues with partners in China"
]
key_achievements = 'Increased fault injection and stability test coverage by over 10x. Improved throughput of electronics manufacturing line by 35% through cycle time reduction analysis using test database.'

["Keyence America"]
employment_period = 'June 2019 - July 2019'
title = "Sales Engineer (Intern)"
responsibilities = [
    "Generated 30+ sales leads on a range of highly technical industrial automation products using a proprietary customer relationship management system",
    "Assisted sales engineers during various in-person sales calls/product demonstrations"
]
key_achievements = "Triggered over $120,000 in sales for vision-based sensors and laser markers."

Rest = """
Center for High Performance Power Electronics
June 2018 - August 2018
Lead Undergraduate Research Assistant
Directed undergraduate research team in developing a cyber-physical power grid testbed
Designed testbed for real-time cyber-attack analysis and defense strategy development
Key Achievement: Resultant research published by IEEE via the North American Power Symposium.

Tech4Imaging LLC
September 2017 -  November 2017
Product Development Engineer (Intern)
Designed and operated test equipment for novel 3D imaging/nondestructive testing technology
Furthered multi-phase mass-flow meter based on ‘electrical capacitance volume tomography’
Modified plumbing system to incorporate stratified flow into a multiphase flow loop for testing
Key Achievement: Determined empirical relationship between capacitance and liquid volume.

"""
